language: php

sudo: false
dist: precise

php:
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
          env: deps=low
    fast_finish: true

before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi

script: composer test

notifications:
  email: false